
"""
Options that can be set by the user.
"""

from enum import Enum

class RefinementStrategy(Enum):
    """ Controls how refinements are done
    """
    SMT = 1          # each refinement is generated by the SMT solver
    EVAL = 2         # each refinement is manually constructed by editing the test, command by command
    EVAL_PER_ARG = 3 # each refinement is manually constructed by editing the test, argument by argument

class Options:
    # Debugging level
    # 0 : no debugging information
    # 1 : minimal debugging information
    # 2 : medium debugging information
    # 3 : maximum debugging information
    DEBUG_LEVEL: int = 1

    # If true a graph of the parse tree is generated.
    GRAPH_PARSE_TREE: bool = False

    # Drives how the refinement of a test is performed.
    REFINEMENT_STRATEGY: RefinementStrategy = RefinementStrategy.EVAL_PER_ARG

    # If true, the Z3 constraints are printed
    PRINT_CONSTRAINTS: bool = False
