block-beta
columns 1
  block:ID
    A["Commands"]
    B["Constraints"]
  end
  space
  C["generate_tests"]
  space
  D["test suite = list of tests"]
  A --> C
  B --> C
  C --> D
  style C fill:#494,stroke:#555,stroke-width:4px
