
"""
Options that can be set by the user.
"""

from enum import Enum

class RefinementStrategy(Enum):
    """ Controls how refinements are done
    """
    SMT = 1     # each refinement is generated by the SMT solver
    PYTHON = 2  # each refinement is manually constructed by editing the test

class Options:
    # If true a graph of the parse tree is generated.
    GRAPH_PARSE_TREE: bool = False

    # Drives how the refinement of a test is performed.
    REFINEMENT_STRATEGY: RefinementStrategy = RefinementStrategy.PYTHON
